### ISSUE TITLE
New uInt64 field

### ISSUE THREAD

**Issue by Kauto** [francisrstokes/construct-js#1]
Would be great to have a Int64/uInt64-Field. We would read it from the database as a string that contains a 64-bit number (f.e. "9223372036854775807") and it is somehow converted into a 64 bit long buffer that contains the value 7FFF,FFFF,FFFF,FFFF.

**Comment by pocesar** [comment]
no binary manipulation library for JS has an out-of-the-box functionality like that, would be a great addition to use BigInt instead of 53bit integers when trying to convert. of course, would either need a flag to enable or a ponyfill

**Comment by francisrstokes** [comment]
Took 2 years but 64-bit support has arrived @Kauto
