### ISSUE TITLE
"Word" size + naming

### ISSUE THREAD

**Issue by Salil999** [francisrstokes/construct-js#2]
Using a `Word` as 16-bits is a bit outdated and I think it can be more generalized + future proof. Is it possible to rename it to something like `iWord16` or `uWord32` to differentiate between signed and unsigned and specify the total number of bits being used?

**Comment by Salil999** [comment]
Similar to #1

**Comment by francisrstokes** [comment]
I wouldn't be against adding those as aliases with an eye to deprecating them in the next version 👍

**Comment by francisrstokes** [comment]
Added fields:

- U8
- U16
- U32
- I8
- I16
- I32

And added a deprecation message in the docs.
